### ISSUE TITLE
'make install' fails

### ISSUE THREAD

**Issue by Gymnae** [jketterl/owrx_connector#1]
It seems that the make file misses a target when being called with `make install`

**Comment by jketterl** [comment]
that's a bit strange, the makefile is generated by cmake. i've been able to run make install with no issues so far.

can you post the complete output of the cmake command? I am suspecting missing dependencies. I should probably put that in the readme.

**Comment by Gymnae** [comment]
You were correct, I missed a buuunch of dependencies and thanks to CentOS 8 - I had to dig deep and compile a bunch of packages myself.
