### ISSUE TITLE
Can you please fix your software

### ISSUE THREAD

**Issue by TGDebug** [jketterl/owrx_connector#10]
Your software is unable to connect to my Ettus Research X310, because it fails to set the antenna

**Comment by jketterl** [comment]
I am unable to fix anything with this little information. Please use the issue template or at least give some more insight as to why you think "my software" is at fault.

I'm assuming you're using the `uhd` type, so the antenna parameter would be sent to the [SoapyUHD](https://github.com/pothosware/SoapyUHD) module. If you think it's not working, it would probably be a good idea to inquire there.
