### ISSUE TITLE
pkg-config file is broken when CMAKE_INSTALL_{INCLUDE,LIB}DIR is absolute

### ISSUE THREAD

**Issue by alexshpilkin** [jketterl/owrx_connector#15]
As per title: `src/lib/owrx-connector.pc.in` has
```
prefix=@CMAKE_INSTALL_PREFIX@
exec_prefix=@CMAKE_INSTALL_PREFIX@
libdir=${exec_prefix}/@CMAKE_INSTALL_LIBDIR@
includedir=${prefix}/@CMAKE_INSTALL_INCLUDEDIR@
```
and so can’t handle absolute paths in `CMAKE_INSTALL_{INCLUDE,LIB}DIR`. This leads to broken .pc files on NixOS in particular.

See “[Concatenating paths when building pkg-config files](https://github.com/jtojnar/cmake-snips#concatenating-paths-when-building-pkg-config-files)” for a thorough discussion of the problem and a suggested fix, or [KDE’s extra-cmake-modules](https://invent.kde.org/frameworks/extra-cmake-modules/-/blob/master/modules/ECMGeneratePkgConfigFile.cmake#L166) for a simpler approach.

**Comment by jketterl** [comment]
more reasons to drop `pkg-config` and switch to cmake exports, i guess...

**Comment by alexshpilkin** [comment]
I mean, if I don’t die before I finish my tour of the 85 CMake-built Nix packages with this problem, I’ll try and come back to you with a patch, so don’t be rash here, but ultimately it’s your choice of course :)

**Comment by alexshpilkin** [comment]
You’re right that there is nothing urgent about this. The specifics of NixOS are not actually that important if you accept it might be useful to have `libdir` etc. *not* be located under the prefix, thus:

```
$ cd /tmp
$ mkdir prefix prefix-bin prefix-include prefix-lib prefix-share
$ git clone https://github.com/jketterl/owrx_connector
[snip]
$ cd owrx_connector
$ git checkout 0.5.0 # I can't build master for unrelated reasons right now but this should do
[snip]
$ mkdir build && cd build
$ cmake -DCMAKE_INSTALL_PREFIX=/tmp/prefix -DCMAKE_INSTALL_BINDIR=/tmp/prefix-bin -DCMAKE_INSTALL_INCLUDEDIR=/tmp/prefix-include -DCMAKE_INSTALL_LIBDIR=/tmp/prefix-lib -DCMAKE_INSTALL_DATAROOTDIR=/tmp/prefix-share ..
[snip warning about rtlsdr vs RTLSDR]
$ make && make install
[snip]
$ grep -r '//tmp/prefix' /tmp/prefix-lib
/tmp/prefix-lib/pkgconfig/owrx-connector.pc:libdir=${exec_prefix}//tmp/prefix-lib
/tmp/prefix-lib/pkgconfig/owrx-connector.pc:includedir=${prefix}//tmp/prefix-include
$ # oops, these will not work.
```
This is also more or less what the Nixpkgs CMake tooling does, except there are a lot of unrelated flags being passed as well.

(To be clear, I’m not the Nixpkgs maintainer for owrx-connector, I’m the person trying to fix these CMake-induced bugs throughout the distro. Nixpkgs is rather chaotic so this is not as unusual as “non-maintainer uploads” would be in other places.)

**Comment by jketterl** [comment]
Thank you for the detailed explanation / example. That really looks like a pretty specific use case.

Quick check for cmake versions show that only Ubuntu Jammy Jellyfish has cmake >= 3.20, so adding the module will probably be the easiest solution.

**Comment by alexshpilkin** [comment]
OK, I have emerged from that pile of miscellaneous software, so here’s one way of fixing this. I shouldn’t have broken anything but it’d probably be better if you checked that.
