### ISSUE TITLE
Compile in raspberry with errors

### ISSUE THREAD

**Issue by dl2kn** [jketterl/owrx_connector#17]
Hello everyone, I wanted to upgrade my openWebRX from version 0.20.3 to 1.2.0. I followed the installation instructions.
Now I get the following errors when installing owrx_connector . 

root@DVMEGA:/home/pi/ham# cd owrx_connector
root@DVMEGA:/home/pi/ham/owrx_connector# mkdir build
root@DVMEGA:/home/pi/ham/owrx_connector# cd build
root@DVMEGA:/home/pi/ham/owrx_connector/build# cmake ..
-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29")
-- Checking for module 'librtlsdr'
--   Found librtlsdr, version v0.5.3-69-g0d82
-- Found rtlsdr: /usr/local/lib/librtlsdr.so
-- Looking for rtlsdr_set_bias_tee
-- Looking for rtlsdr_set_bias_tee - found
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pi/ham/owrx_connector/build
root@DVMEGA:/home/pi/ham/owrx_connector/build#

root@DVMEGA:/home/pi/ham/owrx_connector/build# make
Scanning dependencies of target owrx-connector
[  8%] Building CXX object src/lib/CMakeFiles/owrx-connector.dir/connector.cpp.o
[ 16%] Building CXX object src/lib/CMakeFiles/owrx-connector.dir/iq_connection.cpp.o
[ 25%] Building CXX object src/lib/CMakeFiles/owrx-connector.dir/rtl_tcp_connection.cpp.o
[ 33%] Building CXX object src/lib/CMakeFiles/owrx-connector.dir/control_connection.cpp.o
[ 41%] Building CXX object src/lib/CMakeFiles/owrx-connector.dir/gainspec.cpp.o
[ 50%] Linking CXX shared library libowrx-connector.so
[ 50%] Built target owrx-connector
Scanning dependencies of target rtl_connector
[ 58%] Building CXX object src/app/CMakeFiles/rtl_connector.dir/rtl_connector.cpp.o
/home/pi/ham/owrx_connector/src/app/rtl_connector.cpp: In member function ‘int RtlConnector::set_bias_tee(bool)’:
/home/pi/ham/owrx_connector/src/app/rtl_connector.cpp:296:12: error: ‘rtlsdr_set_bias_te ’ was not declared in this scope
     return rtlsdr_set_bias_tee(dev, (int) new_bias_tee);
            ^~~~~~~~~~~~~~~~~~~
/home/pi/ham/owrx_connector/src/app/rtl_connector.cpp:296:12: note: suggested alternative: ‘rtlsdr_set_if_freq’
     return rtlsdr_set_bias_tee(dev, (int) new_bias_tee);
            ^~~~~~~~~~~~~~~~~~~
            rtlsdr_set_if_freq
make[2]: *** [src/app/CMakeFiles/rtl_connector.dir/build.make:63: src/app/CMakeFiles/rtl_connector.dir/rtl_connector.cpp.o] Fehler 1
make[1]: *** [CMakeFiles/Makefile2:146: src/app/CMakeFiles/rtl_connector.dir/all] Fehler 2
make: *** [Makefile:130: all] Fehler 2
root@DVMEGA:/home/pi/ham/owrx_connector/build#

Can someone help me?

Thanks

73 Michael

**Comment by jketterl** [comment]
Your libraries were tested for `rtlsdr_set_bias_tee()` and the function was present during the test, so bias tee support was enabled.

```
-- Looking for rtlsdr_set_bias_tee
-- Looking for rtlsdr_set_bias_tee - found
```

At a later point, that exact same function is now no longer present.

Please check for multiple installations of the rtl-sdr libraries. Inconsistent setups may be confusing the build system.

**Comment by dl2kn** [comment]
Hello Jakob,

thank you very much, after uninstalling rtl-sdr it worked without any problems.

73 Michael
