### ISSUE TITLE
Command-line issue in rtl_tcp_connector

### ISSUE THREAD

**Issue by gvanem** [jketterl/owrx_connector#21]
I note an issue with `rtl_tcp_connector` parsing it's command-line.
It doesn't seems to use `getopt_long()` for this, since:
 * a `rtl_tcp_connector.exe -cp 445 foo` tries to connect to a `host=445` and fails.
 * a `rtl_tcp_connector.exe -cp445 foo` does work (although `host=foo` does not exist here).
 * and `rtl_tcp_connector.exe  -c1 a-real-host-name xxx` does also work (or `--control=1`).

`getopt.c` would handle this fine; a `-cp 445` and  `-cp445` is the same. I see that `RtlTcpConnector::parse_arguments()` 
checks `argv[optind]` manually. Probably the cause.

But perhaps I mis-understood the usage of this program since a `rtl_tcp_connector.exe --help` does 
not show the real usage AFAICS. Something like:
```
Usage: bin\rtl_tcp_connector.exe [options] <host>

Available options:
  ..
  -p, --port <N>             listen port (default: 4590)
  -f, --frequency <F>        tune to specified frequency  (supporting k,M suffixes?)
  -c, --control <0|1>       control socket port (default: disabled)
  ...
```

would perhaps be nicer.

**Comment by jketterl** [comment]
Judging from your examples, it looks like the basic misunderstanding is that `-c` is not a simple boolean flag, but instead takes a numerical argument, just like `-p`. That means that `-cp 445` simply does not give the connector enough information to do it's job. Instead, you probably want to call it with e.g. `-c 446 -p 445` or similar to make it work.

If you're curious, this is denoted by the `required_argument` flag. This results in the `:` field declaration to be appended to `c` for `getopt_long`. I suppose if anything, the program should fail if `-c` is called without arguments, but not sure if this is even obvious in the code. getopt is a bit weird, and i would probably not use it again.

Also note that the lack of detailed descriptions is down to the fact that this connector is being developed for the single purpose of handling device handling in OpenWebRX, and for this purpose the only requirement is that OpenWebRX knows how to start the connector.

**Comment by gvanem** [comment]
> getopt is a bit weird, and i would probably not use it again.

I think `getopt()` works fine as long as the `--help` page and the `getopt()` / `getopt_long()` code agrees.
It's totally out-of-sync in this program. Perhaps use `CLI11.hpp` instead?

**Comment by jketterl** [comment]
I disagree about things being out of sync. The help option for `-c` is "control socket port" which should imply a numeric argument. The thing that probably throws you off is the "default: disabled" part. The control socket is optional, and if you don't specify a port number the control socket won't be created. If you want to enable the control socket however, you need to pass a port numbeṛ.

I have used CLI11 for csdr, and while it certainly does a better job than getopt, I dislike the "the whole library is in the header" approach.

The next iteration for the connectors however will probably be to integrate them directly with python, eliminating the need to have them as standalone binaries, so I don't think there will be a need for any of this in the future.
