### ISSUE TITLE
Errors when using "make"

### ISSUE THREAD

**Issue by ofadam** [jketterl/owrx_connector#3]
I seem to be getting a whole slew of errors when using "make" – here's my output. Am I missing a dependency? 

agerik@RadioMini:~/owrx_connector/build$ make
Scanning dependencies of target version
[ 16%] Building C object CMakeFiles/version.dir/version.c.o
[ 33%] Linking C static library libversion.a
[ 33%] Built target version
Scanning dependencies of target soapy_connector
[ 50%] Building C object CMakeFiles/soapy_connector.dir/soapy_connector.c.o
/home/agerik/owrx_connector/soapy_connector.c: In function ‘iq_worker’:
/home/agerik/owrx_connector/soapy_connector.c:129:20: warning: return makes pointer from integer without a cast [-Wint-conversion]
             return -3;
                    ^
/home/agerik/owrx_connector/soapy_connector.c:135:20: warning: return makes pointer from integer without a cast [-Wint-conversion]
             return -3;
                    ^
/home/agerik/owrx_connector/soapy_connector.c:152:28: warning: comparison with string literal results in unspecified behavior [-Waddress]
                 if (format == SOAPY_SDR_CS16) {
                            ^~
/home/agerik/owrx_connector/soapy_connector.c:174:35: warning: comparison with string literal results in unspecified behavior [-Waddress]
                 } else if (format == SOAPY_SDR_CF32) {
                                   ^~
/home/agerik/owrx_connector/soapy_connector.c:106:23: warning: unused parameter ‘arg’ [-Wunused-parameter]
 void* iq_worker(void* arg) {
                       ^~~
/home/agerik/owrx_connector/soapy_connector.c: In function ‘control_worker’:
/home/agerik/owrx_connector/soapy_connector.c:290:68: warning: pointer targets in passing argument 3 of ‘accept’ differ in signedness [-Wpointer-sign]
         int sock = accept(listen_sock, (struct sockaddr *)&remote, &rlen);
                                                                    ^
In file included from /home/agerik/owrx_connector/soapy_connector.c:11:0:
/usr/include/i386-linux-gnu/sys/socket.h:232:12: note: expected ‘socklen_t * restrict {aka unsigned int * restrict}’ but argument is of type ‘int *’
 extern int accept (int __fd, __SOCKADDR_ARG __addr,
            ^~~~~~
/home/agerik/owrx_connector/soapy_connector.c: In function ‘main’:
/home/agerik/owrx_connector/soapy_connector.c:536:68: warning: pointer targets in passing argument 3 of ‘accept’ differ in signedness [-Wpointer-sign]
         int client_sock = accept(sock, (struct sockaddr *)&remote, &rlen);
                                                                    ^
In file included from /home/agerik/owrx_connector/soapy_connector.c:11:0:
/usr/include/i386-linux-gnu/sys/socket.h:232:12: note: expected ‘socklen_t * restrict {aka unsigned int * restrict}’ but argument is of type ‘int *’
 extern int accept (int __fd, __SOCKADDR_ARG __addr,
            ^~~~~~
/home/agerik/owrx_connector/soapy_connector.c: In function ‘iq_worker’:
/home/agerik/owrx_connector/soapy_connector.c:214:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
/home/agerik/owrx_connector/soapy_connector.c: In function ‘client_worker’:
/home/agerik/owrx_connector/soapy_connector.c:266:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
/home/agerik/owrx_connector/soapy_connector.c: In function ‘control_worker’:
/home/agerik/owrx_connector/soapy_connector.c:347:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
[ 66%] Linking C executable soapy_connector
[ 66%] Built target soapy_connector
Scanning dependencies of target rtl_connector
[ 83%] Building C object CMakeFiles/rtl_connector.dir/rtl_connector.c.o
/home/agerik/owrx_connector/rtl_connector.c: In function ‘rtlsdr_callback’:
/home/agerik/owrx_connector/rtl_connector.c:102:62: warning: unused parameter ‘ctx’ [-Wunused-parameter]
 void rtlsdr_callback(unsigned char* buf, uint32_t len, void* ctx) {
                                                              ^~~
/home/agerik/owrx_connector/rtl_connector.c: In function ‘iq_worker’:
/home/agerik/owrx_connector/rtl_connector.c:127:23: warning: unused parameter ‘arg’ [-Wunused-parameter]
 void* iq_worker(void* arg) {
                       ^~~
/home/agerik/owrx_connector/rtl_connector.c: In function ‘control_worker’:
/home/agerik/owrx_connector/rtl_connector.c:212:68: warning: pointer targets in passing argument 3 of ‘accept’ differ in signedness [-Wpointer-sign]
         int sock = accept(listen_sock, (struct sockaddr *)&remote, &rlen);
                                                                    ^
In file included from /home/agerik/owrx_connector/rtl_connector.c:10:0:
/usr/include/i386-linux-gnu/sys/socket.h:232:12: note: expected ‘socklen_t * restrict {aka unsigned int * restrict}’ but argument is of type ‘int *’
 extern int accept (int __fd, __SOCKADDR_ARG __addr,
            ^~~~~~
/home/agerik/owrx_connector/rtl_connector.c: In function ‘main’:
/home/agerik/owrx_connector/rtl_connector.c:450:68: warning: pointer targets in passing argument 3 of ‘accept’ differ in signedness [-Wpointer-sign]
         int client_sock = accept(sock, (struct sockaddr *)&remote, &rlen);
                                                                    ^
In file included from /home/agerik/owrx_connector/rtl_connector.c:10:0:
/usr/include/i386-linux-gnu/sys/socket.h:232:12: note: expected ‘socklen_t * restrict {aka unsigned int * restrict}’ but argument is of type ‘int *’
 extern int accept (int __fd, __SOCKADDR_ARG __addr,
            ^~~~~~
/home/agerik/owrx_connector/rtl_connector.c: In function ‘iq_worker’:
/home/agerik/owrx_connector/rtl_connector.c:137:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
/home/agerik/owrx_connector/rtl_connector.c: In function ‘client_worker’:
/home/agerik/owrx_connector/rtl_connector.c:188:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
/home/agerik/owrx_connector/rtl_connector.c: In function ‘control_worker’:
/home/agerik/owrx_connector/rtl_connector.c:267:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
[100%] Linking C executable rtl_connector
[100%] Built target rtl_connector

**Comment by jketterl** [comment]
No real errors, just lots of compiler warnings. For some reason, the cmake package lookup for SoapySDR is modifying compiler settings. I do intend to fix some of them, but it's way to sensitive for my taste. Haven't figured out how to reset it to what it was before.

From what I see, you should be receiving the binaries alright, so I suggest we ignore the warnings for now :wink:

**Comment by jketterl** [comment]
this has been adressed in 84909c53cde78cbf4be408037e31209fbc702ad3 :slightly_smiling_face:
