### ISSUE TITLE
Can not select antenna on LimeSDR USB

### ISSUE THREAD

**Issue by Yume303** [jketterl/owrx_connector#6]
Tried to pass _everything_ with the -a switch, but always got the following error message.
Also, other apps (e.g. GQRX, etc.) works well.

soapy_connector -g 40 -s 2400000 -P 0 -f 438800000 -p 53499 -c 48861 -d driver=lime
[INFO] Make connection: 'LimeSDR-USB [USB 3.0] 9060B00543615'
[INFO] Reference clock 30.72 MHz
[INFO] Device name: LimeSDR-USB
[INFO] Reference: 30.72 MHz
[INFO] LMS7002M register cache: Disabled
[INFO] RX LPF configured
Tuner gain set to 40.00 dB.
setting antenna failed

**Comment by jketterl** [comment]
what antennas are listed by `SoapySDRUtil --probe`? did you try passing those values?

**Comment by Yume303** [comment]
Can be closed, it works with "LNAL" "LNAH" LNAW", many thaks!
