### ISSUE TITLE
compile in raspberry with error

### ISSUE THREAD

**Issue by d9394** [jketterl/owrx_connector#7]
root@DietPi:~/owrx_connector/build# cmake ..
-- Build type not specified: defaulting to release.
-- Configuring done
-- Generating done
-- Build files have been written to: /root/owrx_connector/build
root@DietPi:~/owrx_connector/build# make
[ 33%] Built target version
[ 66%] Built target soapy_connector
[ 83%] Linking C executable rtl_connector
CMakeFiles/rtl_connector.dir/rtl_connector.c.o: In function `control_worker':
rtl_connector.c:(.text+0xac4): undefined reference to `rtlsdr_set_bias_tee'
CMakeFiles/rtl_connector.dir/rtl_connector.c.o: In function `main':
rtl_connector.c:(.text.startup+0x400): undefined reference to `rtlsdr_set_bias_tee'
collect2: error: ld returned 1 exit status
CMakeFiles/rtl_connector.dir/build.make:96: recipe for target 'rtl_connector' failed
make[2]: *** [rtl_connector] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/rtl_connector.dir/all' failed
make[1]: *** [CMakeFiles/rtl_connector.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
root@DietPi:~/owrx_connector/build#
root@DietPi:~/owrx_connector/build# dpkg -l | grep rtlsdr
ii  librtlsdr-dev                        0.5.3-11+rpt1                armhf        Software defined radio receiver for Realtek RTL2832U (development)
ii  librtlsdr0:armhf                     0.5.3-11+rpt1                armhf        Software defined radio receiver for Realtek RTL2832U (library)

**Comment by jketterl** [comment]
Ah, thanks for the report. Looks like an older Raspbian, I just checked a Buster one and that one has version 0.6 of librtlsdr-dev. Is this on Stretch?

Should be possible to fix this, but bias tee will not work then.

**Comment by jketterl** [comment]
Ah, thanks for the report. Looks like an older Raspbian, I just checked a Buster one and that one has version 0.6 of librtlsdr-dev. Is this on Stretch?

Should be possible to fix this, but bias tee will not work then.

**Comment by d9394** [comment]
Yes, maybe old system version:

root@DietPi:~# cat /etc/issue
Raspbian GNU/Linux 9 \n \l
root@DietPi:~# uname -a
Linux DietPi 4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l GNU/Linux
root@DietPi:~# cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

**Comment by d9394** [comment]
I have make the librtlsdr using the newest source from git://git.osmocom.org/rtl-sdr.git, and then owrx_connector also make successful.

**Comment by jketterl** [comment]
I have to fix this same issue in a PR i opened on SoapyRTLSDR, should be easy to backport the solution to this, and I'd also like to keep Stretch supported for now, so reopening :)
