### ISSUE TITLE
How to use rtl_tcp_connector

### ISSUE THREAD

**Issue by OE4AMW** [jketterl/owrx_connector#9]
Hi,

I am quite new to openwebrx, and today found that there is a rtl_tcp_connector ( https://github.com/jketterl/owrx_connector/blob/develop/rtl_tcp_connector.c ) and it sounds promising.
How can I configure/use it?
Is it already part of the docker-builds?

**Comment by OE4AMW** [comment]
I found out that it is included in the latest docker-builds, and that it connects to the rtl_tcp - server with followig config:
```
    "rtltcp": {
        "name": "RTL-TCP",
        "type": "rtl_tcp",
        "ppm": 0,
        "remote": "host:port",
```
however, the waterfall is quite "pale", and no signal is found.

**Comment by OE4AMW** [comment]
Two further hints to configure rtl_tcp_connector:
1. While the command-line argument `-g 0` in rtl_tcp enables AGC, in rtl_tcp_connector it disables AGC, and sets gain to 0.
To enable AGC, it needs to be configured explicitly to 'auto':
`"rf_gain": "auto"`
2. Care needs to be taken when configuring `samp_rate` - rtl_tcp does not report any errors when setting an invalid rate, and stays at the default, while OpenWebRX inprets it according to its own configuration. This is another source of "strange" effects.
_This is btw. the valid range:_
```
	/* check if the rate is supported by the resampler */
	if ((samp_rate <= 225000) || (samp_rate > 3200000) ||
	   ((samp_rate > 300000) && (samp_rate <= 900000))) {
		fprintf(stderr, "Invalid sample rate: %u Hz\n", samp_rate);
		return -EINVAL;
	}
```

**Comment by jketterl** [comment]
This is not a place for questions, stories or field reports. The issues sections is to file bug reports on the owrx_connector package. Please check out the OpenWebRX groups.io mailing list at https://groups.io/g/openwebrx
